### PR TITLE
Added multiple series support for all chart types.

### PR DESCRIPTION
**Pull request by ghost**
Apologies for recreating the PR at #23 : I accidentally nuked my old repository both locally and online, so I had to rewrite again. I will re-add tests again in the next commit.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @Ashvith, thanks for the update. For scatter charts, have you tried two numeric columns?

**Comment by Ashvith** [comment]
> Hey @Ashvith, thanks for the update. For scatter charts, have you tried two numeric columns?

- I tried the `cars.csv` dataset, and it works just fine.

- I've seen that when I used a dataset without the `group` parameter, it works the same way, except that it doesn't add color.

Are these normal behaviour?

And I am guessing that we might need to add another `dataframe` for `scatter` type?

**Comment by ankane** [comment]
I'm not sure I understand. Can you provide some examples of what you've tried?

**Comment by Ashvith** [comment]
> I'm not sure I understand. Can you provide some examples of what you've tried?

These are the datasets I've used. I've checked the working ones.

- [x]  [cars.csv](https://gist.github.com/noamross/e5d3e859aa0c794be10b)

- [ ] [stocks.csv](https://raw.githubusercontent.com/vega/datalib/master/test/data/stocks.csv)
- [ ] Custom dataframe 1
```ruby
df = Rover::DataFrame
    .new({"category" => ["A", "A", "A", "B", "B", "B", "C", "C", "C"], 
          "group" => ["x", "y", "z", "x", "y", "z", "x", "y", "z"],
          "value" => [0.1, 0.6, 0.9, 0.7, 0.2, 1.1, 0.6, 0.1, 0.2]})
```
- [x] Custom dataframe 2
```ruby
  df = Rover::DataFrame
    .new({"category" => ["A", "A", "A", "B", "B", "B", "C", "C", "C"], 
          "group" => [1, 2, 3, 1, 2, 3, 1, 2, 3],
          "value" => [0.1, 0.6, 0.9, 0.7, 0.2, 1.1, 0.6, 0.1, 0.2]})
```

**Comment by ankane** [comment]
Thanks @Ashvith! The middle two dataset aren't working for scatter plots since there aren't two numeric columns.

**Comment by Ashvith** [comment]
@ankane I'll check that out today if I can spare some time.

**Pull request merged**
