### PR TITLE
Improve inspect

### PR DESCRIPTION
**Pull request by heronshoes**
This is a PR for #36.

Currently NaN / nil count is disabled. We can use it easily when #35 impremented.

### CODE REVIEW

**Comment by heronshoes** [comment]
For last commit about `tally`, I have small benchmark below.
```
n, m = 1000000, 100
df = Rover::DataFrame.new({
    int:   Numo::Int32.new(n).rand(m),
    float: Numo::DFloat.new(n).rand(m).round,
    str:   Numo::Int32.new(n).rand(65,91).to_a.map(&:chr),
    bit:   (Numo::DFloat.new(n).rand(1) > 0.5),
  })
Benchmark.ips do |x|
  x.report("original")  { df.vectors.each {|k, v| v.tally} }
  x.report("new tally") { df.vectors.each {|k, v| v.new_tally} }
  x.compare!
end; nil
```
#=> results
```
Warming up --------------------------------------
            original     1.000  i/100ms
           new tally     1.000  i/100ms
Calculating -------------------------------------
            original      2.251  (± 0.0%) i/s -     12.000  in   5.335517s
           new tally      4.096  (± 0.0%) i/s -     21.000  in   5.129690s

Comparison:
           new tally:        4.1 i/s
            original:        2.3 i/s - 1.82x  (± 0.00) slower
```

**Comment by ankane** [comment]
Hey @heronshoes, thanks for the PRs! Still need to spend some time to review, but can you create a separate PR for the tally performance improvement?

**Comment by heronshoes** [comment]
Hi @ankane, thanks for the comment. Sure, I will separate PR for tally.

Also I will update other part of this PR because this code should be refined.

**Comment by heronshoes** [comment]
Hi @ankane , this request is now far from the HEAD. You can close this request anytime if you want. If you need this feature I will very happy to refine this code.

After make this PR, I have started my own project of Ruby's DataFrame library [RedAmber](https://github.com/heronshoes/red_amber). I am very appreciated to get a lot of  inspirations from Rover. The feature in this PR is implemented as `#tdr` method in `RedAmber`. I believe it is useful to use in the exploratory data processing. It keeps Vectors as row vectors, shows keys and types at a glance, shows levels for the 'factor-like' variables and shows the number of abnormal values like NaN and nil.

I would be very happy if you could drop in at my repository. Thanks.

**Comment by ankane** [comment]
Hi @heronshoes, sorry I never got around to reviewing this, #38, and #39.

RedAmber looks great (nice API and lots of functionality)!!

Have recently been working on [Polars Ruby](https://github.com/ankane/polars-ruby), which uses Arrow as well.

**Comment by heronshoes** [comment]
Hi @ankane, I think Polars Ruby is a great work and is promising in performance. I think the expr and lazy frames in Polars are very nice!!

**Pull request closed without merging**
