### PR TITLE
Improve speed of csv_to_df

### PR DESCRIPTION
**Pull request by pkeshkamat**
I made a new pull request just because the last one had 12+ commits which were all named the same.
This should pass the tests.
I removed the custom csv parsing logic and with the csv module this gets around 7.5 seconds on average
```
Measure Mode: wall_time
Thread ID: 400
Fiber ID: 380
Total: 7.261605
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
 17.21      2.221     1.250     0.000     0.971    30822  *Array#map                      
 16.70      3.318     1.212     0.000     2.106     1412   String#each_line               
 16.67      2.190     1.210     0.000     0.979    30108  *Array#each                     
  7.46      0.542     0.542     0.000     0.000  2997259   String#tr                      
  5.53      0.583     0.402     0.000     0.181      478   Array#all?                     
  5.36      0.389     0.389     0.000     0.000  7140853   Kernel#is_a?                   
  4.32      0.314     0.314     0.000     0.000    14932   String#split                   
  3.85      0.279     0.279     0.000     0.000  2997498   Integer#zero?                  <internal:integer>:146
  3.50      0.254     0.254     0.000     0.000  2978533   String#to_f                    
  3.21      0.233     0.233     0.000     0.000    14931   Array#zip                      
  2.82      0.205     0.205     0.000     0.000  2997498   String#count                   
  2.74      0.287     0.199     0.000     0.087      239   <Class::Numo::DFloat>#cast     
  2.57      0.187     0.187     0.000     0.000  3598373   Array#push                     
  2.40      0.174     0.174     0.000     0.000  3569921   Array#last                     
  2.38      0.173     0.173     0.000     0.000  3568748   String#freeze                  
  1.20      0.087     0.087     0.000     0.000      239   Numo::DFloat#allocate          
  0.69      0.050     0.050     0.000     0.000    14932   String#delete_suffix           
  0.21      3.909     0.015     0.000     3.894        1   <Module::Rover>#csv_to_df      /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover.rb:45
  0.21      0.015     0.015     0.000     0.000     1412   IO#eof?                        
  0.13      1.238     0.010     0.000     1.228    14932   CSV::Parser#emit_row           /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:1105
  0.09      2.331     0.006     0.000     2.325    17074  *Class#new                      
  0.08      1.217     0.006     0.000     1.211    14931   CSV::Row#initialize            /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/row.rb:30
  0.06      0.006     0.004     0.000     0.002    14933   CSV::Parser::InputsScanner#keep_start /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:167
  0.04      0.409     0.003     0.000     0.405    14931   CSV::Row#fields                /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/row.rb:451
  0.04      0.003     0.003     0.000     0.000    29864   String#include?                
  0.04      0.023     0.003     0.000     0.020     1413   CSV::Parser::InputsScanner#read_chunk /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:206
  0.04      0.006     0.003     0.000     0.003    14932   CSV::FieldsConverter#convert   /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/fields_converter.rb:47
  0.04      0.004     0.003     0.000     0.001    14933   CSV::Parser::InputsScanner#keep_drop /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:197
  0.04      0.003     0.003     0.000     0.000    14932   CSV::FieldsConverter#need_convert? /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/fields_converter.rb:79
  0.04      0.003     0.003     0.000     0.000    34098   StringScanner#pos              
  0.03      0.793     0.002     0.000     0.791    15171   Enumerable#each_with_index     
  0.03      0.009     0.002     0.000     0.006        1   Kernel#p                       
  0.03      0.002     0.002     0.000     0.000    31274   StringScanner#pos=             
  0.02      0.002     0.002     0.000     0.000    32684   String#bytesize                
  0.02      0.002     0.002     0.000     0.000     1412   IO#gets                        
  0.02      0.002     0.002     0.000     0.000    16343   String#end_with?               
  0.02      0.001     0.001     0.000     0.000    14931   CSV::Row#header_row?           /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/row.rb:61
  0.02      3.343     0.001     0.000     3.342        1   CSV::Parser::InputsScanner#each_line /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:96
  0.01      0.001     0.001     0.000     0.000    14935   Array#pop                      
  0.01      0.001     0.001     0.000     0.000     4780   Float#to_s                     
  0.01      0.001     0.001     0.000     0.000     2868   String#%                       
  0.01      0.001     0.001     0.000     0.000     1412   String#valid_encoding?         
  0.01      0.001     0.001     0.000     0.000     1412   StringScanner#rest             
  0.01      1.113     0.001     0.000     1.112        2   Hash#each                      
  0.01      1.106     0.001     0.000     1.106      717   Rover::Vector#cast_data        /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:336
  0.01      0.001     0.001     0.000     0.000      478   Numo::DFloat#to_a              
  0.01      0.001     0.000     0.000     0.000     1413   Kernel#dup                     
  0.00      0.000     0.000     0.000     0.000     1411   String#byteslice               
  0.00      0.001     0.000     0.000     0.000     2130   Kernel#initialize_dup          
  0.00      0.000     0.000     0.000     0.000     1412   StringScanner#initialize       
  0.00      1.107     0.000     0.000     1.107      717   Rover::Vector#initialize       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:24
  0.00      0.000     0.000     0.000     0.000     1656   Kernel#respond_to?             
  0.00      0.000     0.000     0.000     0.000     1649   Integer#-@                     <internal:integer>:6
  0.00      0.000     0.000     0.000     0.000      208   Array#join                     
  0.00      0.000     0.000     0.000     0.000     1417   Module#===                     
  0.00      0.000     0.000     0.000     0.000      478   Numo::DFloat#[]                
  0.00      0.000     0.000     0.000     0.000     2868   Integer#to_s                   
  0.00      0.000     0.000     0.000     0.000     2868   String#size                    
  0.00      0.000     0.000     0.000     0.000      239   Class#allocate                 
  0.00      0.001     0.000     0.000     0.001      478   Rover::Vector#to_a             /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:41
  0.00      0.000     0.000     0.000     0.000     1654   Array#first                    
  0.00      0.000     0.000     0.000     0.000     1412   String#initialize_copy         
  0.00      0.000     0.000     0.000     0.000      719   Rover::Vector#size             /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:51
  0.00      0.001     0.000     0.000     0.000      239   Rover::Vector#last             /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:265
  0.00      0.000     0.000     0.000     0.000     1411   StringScanner#string           
  0.00      0.001     0.000     0.000     0.001      239   Rover::Vector#first            /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/vector.rb:257
  0.00      0.000     0.000     0.000     0.000        2   Hash#each_key                  
  0.00      0.000     0.000     0.000     0.000      239   Rover::DataFrame#to_vector     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:579
  0.00      0.000     0.000     0.000     0.000     1198   String#to_s                    
  0.00      0.000     0.000     0.000     0.000      718   Array#initialize_copy          
  0.00      0.000     0.000     0.000     0.000      719   Numo::NArray#size              
  0.00      0.000     0.000     0.000     0.000      717   Numo::NArray#ndim              
  0.00      0.000     0.000     0.000     0.000      239   Rover::DataFrame#check_key     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:488
  0.00      0.000     0.000     0.000     0.000      239   Module#<=                      
  0.00      0.000     0.000     0.000     0.000      239   Array#max                      
  0.00      0.000     0.000     0.000     0.000        1   File#initialize                
  0.00      0.000     0.000     0.000     0.000      239   Array#to_a                     
  0.00      0.000     0.000     0.000     0.000      238   Array#sum                      
  0.00      7.262     0.000     0.000     7.262        1   [global]#                      main.rb:5
  0.00      0.000     0.000     0.000     0.000      208   String#*                       
  0.00      0.000     0.000     0.000     0.000       16   Integer#times                  
  0.00      1.107     0.000     0.000     1.107        1   Rover::DataFrame#initialize    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:3
  0.00      0.000     0.000     0.000     0.000        1   IO#close                       
  0.00      0.000     0.000     0.000     0.000        7   Regexp#initialize              
  0.00      0.000     0.000     0.000     0.000        1   Array#uniq                     
  0.00      1.994     0.000     0.000     1.994        1   <Module::Rover>#csv_to_numeric /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover.rb:33
  0.00      0.000     0.000     0.000     0.000        1   Rover::DataFrame#process_args  /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:614
  0.00      0.000     0.000     0.000     0.000        3   Array#shift                    
  0.00      3.344     0.000     0.000     3.344        1   CSV#read                       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2379
  0.00      0.000     0.000     0.000     0.000        1   CSV#initialize                 /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1732
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_separators /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:487
  0.00      0.000     0.000     0.000     0.000       17   String#encode                  
  0.00      0.006     0.000     0.000     0.006        1   Rover::DataFrame#inspect       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:288
  0.00      7.253     0.000     0.000     7.253        1   <Module::Rover>#read_csv       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover.rb:12
  0.00      3.344     0.000     0.000     3.344        1   <Class::CSV>#open              /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1412
  0.00      0.000     0.000     0.000     0.000        3   Hash#values                    
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#resolve_row_separator /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:573
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare            /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:356
  0.00      3.343     0.000     0.000     3.343        2   CSV::Parser#parse              /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:318
  0.00      0.000     0.000     0.000     0.000        1   <Class::StringIO>#new          
  0.00      0.000     0.000     0.000     0.000        2   CSV::FieldsConverter#initialize /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/fields_converter.rb:13
  0.00      0.000     0.000     0.000     0.000        1   Kernel#require                 <internal:/Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:36
  0.00      0.000     0.000     0.000     0.000        1   StringIO#initialize            
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_quote_character /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:396
  0.00      0.000     0.000     0.000     0.000        5   Hash#merge                     
  0.00      1.577     0.000     0.000     1.577        1   Enumerator#with_index          
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_quoted     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:533
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_skip_lines /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:428
  0.00      0.000     0.000     0.000     0.000        1   CSV#close                      /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/forwardable.rb:229
  0.00      0.417     0.000     0.000     0.417        1   CSV::Table#to_a                /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/table.rb:572
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_variable   /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:370
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#detect_row_separator /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:613
  0.00      0.000     0.000     0.000     0.000        1   CSV::Table#headers             /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/table.rb:139
  0.00      0.000     0.000     0.000     0.000        1   CSV::Table#initialize          /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/table.rb:31
  0.00      0.000     0.000     0.000     0.000        3   String#[]                      
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#build_scanner      /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:742
  0.00      0.000     0.000     0.000     0.000        1   Enumerable#find                
  0.00      0.000     0.000     0.000     0.000        3   CSV#parser                     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2614
  0.00      0.000     0.000     0.000     0.000        2   Hash#keys                      
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_header     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:651
  0.00      0.000     0.000     0.000     0.000        1   StringIO#read                  
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_strip      /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:445
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser::InputsScanner#initialize /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:87
  0.00      3.343     0.000     0.000     3.343        1   CSV::Parser#parse_quotable_loose /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:823
  0.00      0.000     0.000     0.000     0.000        2   CSV#build_fields_converter     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2606
  0.00      0.000     0.000     0.000     0.000        1   Rover::DataFrame#size          /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:109
  0.00      3.344     0.000     0.000     3.344        1   Enumerable#to_a                
  0.00      3.344     0.000     0.000     3.344        1   CSV#each                       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2344
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_unquoted   /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:560
  0.00      0.000     0.000     0.000     0.000        3   String#index                   
  0.00      0.000     0.000     0.000     0.000        4   <Class::Regexp>#escape         
  0.00      0.000     0.000     0.000     0.000        3   Array#collect                  
  0.00      0.000     0.000     0.000     0.000        1   BasicObject#initialize         
  0.00      0.000     0.000     0.000     0.000        1   CSV::Row#headers               /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/row.rb:81
  0.00      0.000     0.000     0.000     0.000        2   CSV#normalize_converters       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2529
  0.00      0.000     0.000     0.000     0.000        1   CSV#build_header_fields_converter /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2588
  0.00      0.000     0.000     0.000     0.000        1   <Module::Rover>#csv_options    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover.rb:39
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#use_headers?       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:350
  0.00      0.000     0.000     0.000     0.000        1   Rover::DataFrame#keys          /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rover-df-0.2.7/lib/rover/data_frame.rb:133
  0.00      0.000     0.000     0.000     0.000        1   Gem::Specification#==          /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1318
  0.00      0.000     0.000     0.000     0.000        1   Array#-                        
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#may_quoted?        /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:693
  0.00      0.000     0.000     0.000     0.000        1   <Module::Gem>#find_unresolved_default_spec /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems.rb:1230
  0.00      0.000     0.000     0.000     0.000        1   CSV#parser_options             /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2618
  0.00      3.344     0.000     0.000     3.344        1   <Class::CSV>#read              /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1656
  0.00      0.000     0.000     0.000     0.000        3   Kernel#block_given?            
  0.00      0.001     0.000     0.000     0.000        1   CSV#parser_enumerator          /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2623
  0.00      3.343     0.000     0.000     3.343        1   Enumerator#each                
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#initialize         /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:258
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#headers            /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:290
  0.00      0.000     0.000     0.000     0.000        1   Kernel#gem_original_require    
  0.00      0.000     0.000     0.000     0.000        1   <Class::IO>#open               
  0.00      0.000     0.000     0.000     0.000        1   CSV#raw_encoding               /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2562
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_line       /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:637
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#adjust_headers     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:683
  0.00      0.000     0.000     0.000     0.000        2   String#==                      
  0.00      0.000     0.000     0.000     0.000        1   CSV#header_fields_converter    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2584
  0.00      0.000     0.000     0.000     0.000        1   CSV#build_parser_fields_converter /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2576
  0.00      0.000     0.000     0.000     0.000        1   Hash#to_h                      
  0.00      0.000     0.000     0.000     0.000        1   CSV#determine_encoding         /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2514
  0.00      0.000     0.000     0.000     0.000        2   CSV::FieldsConverter#need_static_convert? /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/fields_converter.rb:75
  0.00      0.000     0.000     0.000     0.000        1   CSV#parser_fields_converter    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:2572
  0.00      0.000     0.000     0.000     0.000        2   String#+                       
  0.00      0.000     0.000     0.000     0.000        1   Array#any?                     
  0.00      0.000     0.000     0.000     0.000        2   Gem::Specification#platform    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:2177
  0.00      0.000     0.000     0.000     0.000        1   <Class::Gem::Specification>#unresolved_deps /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1254
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_parser     /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:689
  0.00      0.000     0.000     0.000     0.000        2   Monitor#mon_owned?             
  0.00      0.000     0.000     0.000     0.000        1   BasicObject#!=                 
  0.00      0.000     0.000     0.000     0.000        2   NilClass#===                   
  0.00      0.000     0.000     0.000     0.000        3   Hash#delete                    
  0.00      0.000     0.000     0.000     0.000        1   Kernel#to_enum                 
  0.00      0.000     0.000     0.000     0.000        1   Kernel#class                   <internal:kernel>:18
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#quote_character    /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:274
  0.00      0.000     0.000     0.000     0.000        1   Kernel#__method__              
  0.00      0.000     0.000     0.000     0.000        1   CSV::Parser#prepare_backslash  /Users/pkeshkamat/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv/parser.rb:413
  0.00      0.000     0.000     0.000     0.000        1   Monitor#exit                   
  0.00      0.000     0.000     0.000     0.000        1   Monitor#enter                  
  0.00      0.000     0.000     0.000     0.000        1   FalseClass#===                 
  0.00      0.000     0.000     0.000     0.000        1   Comparable#==                  
  0.00      0.000     0.000     0.000     0.000        1   IO#internal_encoding           
  0.00      0.000     0.000     0.000     0.000        1   IO#external_encoding           
```
If you would like, I can add it back in. With it it averages around 4.5 seconds.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @pkeshkamat, thanks for the update. Unfortunately, this breaks backwards compatibility (the modified test case and changes integer columns to floats - see new test case on master). I think it's best to focus on removing the `headers` option rather than rewriting the converters logic. If there are performance improvements to the converters logic that don't break existing behavior, it'd be best to submit them to Ruby.

Also, there are still a lot of unnecessary changes (changes to blank lines, unnecessary lines removed, `unnamed_suffix` logic) and the spacing isn't consistent with the code it replaces (`var=value` instead of `var = value`). Please double check all of this is fixed before another review.

Re custom parsing: using `split` is faster, but it doesn't handle quoting, so it'll parse files with quotes incorrectly.

**Comment by pkeshkamat** [comment]
> If there are performance improvements to the converters logic that don't break existing behavior, it'd be best to submit them to Ruby.

I'll look at the csv repository and see if there's any improvements to be made there.

> Also, there are still a lot of unnecessary changes (changes to blank lines, unnecessary lines removed, `unnamed_suffix` logic) and the spacing isn't consistent with the code it replaces (`var=value` instead of `var = value`). Please double check all of this is fixed before another review.

I fixed this, if there's any other particulars feel free to edit the changes.


> Unfortunately, this breaks backwards compatibility (the modified test case and changes integer columns to floats - see new test case on master).

I changed the test function because there was a comment there saying to change "" to "unnamed4"; as for the float/integer, i changed to_i to to_f
If you want to remove the new conversions entirely, I can always just make another pull request with the 13 second version, using the numeric converter.

**Comment by ankane** [comment]
Great, the style looks much better. The todo is for version 0.3.0, so please don't change it now. And yes, please remove the converter changes since it's a breaking change (see the latest tests on master for one example, but there may be others).

**Comment by pkeshkamat** [comment]
Done; passes rake tests.

**Comment by ankane** [comment]
Great, looks like there's one more issue due to the change in the `keys` logic. Just pushed a new test.

**Comment by pkeshkamat** [comment]
> Great, looks like there's one more issue due to the change in the `keys` logic. Just pushed a new test.

Fixed

**Comment by ankane** [comment]
Hey @pkeshkamat, just pushed a change that speeds things up by ~3x in my testing. Thanks for driving this.

**Pull request closed without merging**
