### PR TITLE
Improve speed of csv_to_df and read_csv

### PR DESCRIPTION
**Pull request by pkeshkamat**
Regarding [this issue](https://github.com/ankane/rover/issues/20), I wrote this and found it was faster.
```ruby
h = {}
unnamed_suffix = 1
data = {}
table.headers.each_with_index{|table_key,index|
  key=table_key.to_s
  if table_key.empty? then
    key="unnamed"
    while h.include?(k)
      key="unnamed#{unnamed_suffix}"
      unnamed_suffix+=1
    end
  end
  data[key]=[]
  h[index]=key
}
table.instance_variable_get(:@table).each{|x|
  x=x.fields
  x.each_with_index{|val,index|
    data[h[index]].push(val)
  }
}
```
When I used ruby-prof, it showed a time change from ~28 seconds to ~12 seconds on the dataset linked in the above issue.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @pkeshkamat, thanks for the PR! Can you share details from ruby-prof of what makes this approach faster? Also, please keep the changeset to a minimum and follow the existing style.

**Comment by ankane** [comment]
Also, just pushed a fix to CI if you merge the latest master.

**Comment by pkeshkamat** [comment]
```
Measure Mode: wall_time
Thread ID: 400
Fiber ID: 380
Total: 12.253749
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
 33.84      7.452     4.147     0.000     3.306  3598674  *Array#each                     
 10.79      6.771     1.322     0.000     5.449    29865   Array#collect                  
  9.90      9.978     1.213     0.000     8.765     1397   String#each_line               
  6.87      0.842     0.842     0.000     0.000 14108551   Kernel#is_a?                   
  5.88      0.896     0.721     0.000     0.175  2997547   Kernel#Integer                 
  3.57      0.438     0.438     0.000     0.000  3433912   String#encode                  
  3.38      0.591     0.415     0.000     0.176    15825   Array#map                      
  3.33      0.587     0.408     0.000     0.179      427   Array#all?                     
  2.27      0.278     0.278     0.000     0.000  2997786   Integer#zero?                  <internal:integer>:146
  2.17      0.265     0.265     0.000     0.000    14938   String#split                   
  2.08      0.255     0.255     0.000     0.000  4004857   Proc#arity                     
  2.03      0.248     0.248     0.000     0.000   570962   BasicObject#method_missing     
  1.80      0.221     0.221     0.000     0.000    14931   Array#zip                      
  1.68      0.206     0.206     0.000     0.000  2997786   String#count                   
  1.62      0.198     0.198     0.000     0.000  3598373   Array#push                     
  1.43      0.176     0.176     0.000     0.000  3569918   Array#last                     
  1.41      0.173     0.173     0.000     0.000  3568748   String#freeze                  
  1.13      0.140     0.138     0.000     0.001      164   <Class::Numo::DFloat>#cast     
  0.72      0.089     0.089     0.000     0.000   454936   String#inspect                 
  0.62      0.082     0.075     0.000     0.007   436348   Kernel#Float                   <internal:kernel>:171
  0.58      0.071     0.071     0.000     0.000  1025899   Exception#backtrace            
  0.56      0.068     0.068     0.000     0.000  1027559   Module#===                     
  0.49      0.060     0.060     0.000     0.000  1025899   Exception#exception            
  0.49      0.060     0.060     0.000     0.000       72   <Class::Numo::Int64>#cast      
  0.28      0.034     0.034     0.000     0.000   454935   Exception#initialize           
  0.12      0.015     0.015     0.000     0.000     1397   IO#eof?                        
  0.10      0.012     0.012     0.000     0.000        2   <Class::Time>#now  
  ```
  
  ```
  Measure Mode: wall_time
Thread ID: 400
Fiber ID: 380
Total: 28.807001
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
 33.35      9.608     9.608     0.000     0.000  7137018   Array#assoc                    
 15.49     16.402     4.462     0.000    11.941  7137018   CSV::Row#[]       
 12.30     23.873     3.545     0.000    20.329  3583742  *Array#each                     
  6.61      1.905     1.905     0.000     0.000 35519605   Kernel#is_a?                   
  5.11     17.875     1.472     0.000    16.403     1373   Array#map                      
  4.67      6.759     1.345     0.000     5.413    29865   Array#collect                  
  4.31     10.038     1.241     0.000     8.797     1397   String#each_line               
  2.68     10.381     0.773     0.000     9.608  7137018   Kernel#public_send             
  2.47      0.884     0.710     0.000     0.174  2997547   Kernel#Integer                 
  1.52      0.438     0.438     0.000     0.000  7138427   Array#last                     
  1.48      0.611     0.425     0.000     0.185      427   Array#all?                     
  1.43      0.411     0.411     0.000     0.000  3433912   String#encode                  
  1.04      0.298     0.298     0.000     0.000    14938   String#split                   
  0.99      0.284     0.284     0.000     0.000  2997786   Integer#zero?                  <internal:integer>:146
  0.94      0.270     0.270     0.000     0.000   570962   BasicObject#method_missing     
  0.82      0.237     0.237     0.000     0.000    14931   Array#zip                      
  0.79      0.227     0.227     0.000     0.000  4004857   Proc#arity                     
  0.72      0.209     0.209     0.000     0.000  2997786   String#count                   
  0.64      0.183     0.183     0.000     0.000  3568748   String#freeze                  
  0.50      0.145     0.145     0.000     0.000      164   <Class::Numo::DFloat>#cast     
  0.29      0.085     0.085     0.000     0.000   454937   String#inspect                 
  0.28      0.088     0.082     0.000     0.007   436348   Kernel#Float                   <internal:kernel>:171
  0.25      0.071     0.071     0.000     0.000  1027559   Module#===                     
  0.24      0.070     0.070     0.000     0.000  1025899   Exception#backtrace            
  0.22      0.063     0.063     0.000     0.000  1025899   Exception#exception            
  0.22      0.077     0.063     0.000     0.015       72   <Class::Numo::Int64>#cast      
  0.13      0.036     0.036     0.000     0.000   454935   Exception#initialize           
  0.07      0.021     0.021     0.000     0.000     1397   IO#eof?                        
  0.05      0.014     0.014     0.000     0.000       72   Numo::Int64#allocate
  ```

**Comment by pkeshkamat** [comment]
I think a majority of the time is being caused by the CSV::Table.each method. Rather than doing that, CSV::Table.to_a returns a table with all of the headers in the first row (which could also be accessed by with .headers instead of using .map). The subsequent rows have the data.

**Comment by Ashvith** [comment]
This PR looks fine to me. Is there something missing @ankane ?

**Comment by pkeshkamat** [comment]
@ankane,
I found that a good portion of the time was being spent on actually reading the csv file; 
```ruby
    def read_csv(path, types: nil, use_csv_module: false, **options)
      data=[]
      if !use_csv_module then
      line_separator=options[:line_separator]||"\n"
      character_separator=options[:character_separator]||","
      fill=options[:blank_filler]
      csv_content=File.read(path)
      lines=csv_content.split(line_separator)
      data.push(lines.shift.split(character_separator))
      lines.each{|line|
      data.push(line.split(character_separator).map{|cell|
        cell.tr("^0-9","")==cell ? cell.to_f : fill
      })
      }
    else
      require "csv"
      data=CSV.read(path, **csv_options(options)).to_a
    end
      csv_to_df(data, types: types, headers: options[:headers])
    end
```
If you would like, I can add this in to the Pull Request
Here is the ruby_prof info
```
Measure Mode: wall_time
Thread ID: 400
Fiber ID: 380
Total: 4.703397
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
 28.29      2.346     1.331     0.000     1.015    15171   Array#map                      
 17.92      3.397     0.843     0.000     2.554    14935  *Array#each                     
 13.52      0.636     0.636     0.000     0.000  3568509   String#tr                      
 10.78      0.736     0.507     0.000     0.229      478   Array#all?                     
  8.07      0.379     0.379     0.000     0.000  3549783   String#to_f                    
  5.80      0.273     0.273     0.000     0.000  3583441   Array#push                     
  5.60      0.264     0.263     0.000     0.001      239   <Class::Numo::DFloat>#cast     
  4.89      0.230     0.230     0.000     0.000    14933   String#split                   
  4.88      0.229     0.229     0.000     0.000  3569708   Kernel#is_a?                   
  0.08      0.004     0.004     0.000     0.000        1   <Class::IO>#read               
  0.08      1.110     0.004     0.000     1.106    14932   Enumerable#each_with_index     
  0.06      2.410     0.003     0.000     2.407        1   <Module::Rover>#csv_to_df      
  0.01      0.000     0.000     0.000     0.000      239   Numo::DFloat#allocate          
  0.01      1.294     0.000     0.000     1.294      239   Rover::Vector#cast_data        
  0.01      1.295     0.000     0.000     1.295        1   Hash#each                      
  0.00      1.294     0.000     0.000     1.294      239   Rover::Vector#initialize       
  0.00      1.295     0.000     0.000     1.295      240  *Class#new                      
  0.00      0.000     0.000     0.000     0.000        2   Hash#each_key                  
  0.00      0.000     0.000     0.000     0.000      239   Class#allocate                 
  0.00      0.000     0.000     0.000     0.000      239   Rover::DataFrame#to_vector     
  0.00      0.000     0.000     0.000     0.000      240   Rover::Vector#size             
  0.00      0.000     0.000     0.000     0.000      239   Kernel#initialize_dup          
  0.00      0.000     0.000     0.000     0.000      239   Kernel#respond_to?             
  0.00      0.000     0.000     0.000     0.000      239   Rover::DataFrame#check_key     
  0.00      0.000     0.000     0.000     0.000      240   Numo::NArray#size              
  0.00      0.000     0.000     0.000     0.000      239   Numo::NArray#ndim              
  0.00      0.000     0.000     0.000     0.000      239   Array#initialize_copy          
  0.00      0.000     0.000     0.000     0.000      239   Array#to_a                     
  0.00      4.703     0.000     0.000     4.703        1   <Module::Rover>#read_csv       
  0.00      0.000     0.000     0.000     0.000      239   Module#<=                      
  0.00      0.000     0.000     0.000     0.000      239   String#to_s                    
  0.00      1.295     0.000     0.000     1.295        1   Rover::DataFrame#initialize    
  0.00      4.703     0.000     0.000     4.703        1   [global]#                      main.rb:5
  0.00      0.000     0.000     0.000     0.000        1   Hash#to_h                      
  0.00      0.000     0.000     0.000     0.000        1   Rover::DataFrame#process_args  
  0.00      0.000     0.000     0.000     0.000        1   Array#uniq                     
  0.00      0.000     0.000     0.000     0.000        2   Array#shift                    
  0.00      0.000     0.000     0.000     0.000        2   Hash#values                    
  0.00      0.000     0.000     0.000     0.000        1   Enumerable#find                
  0.00      0.000     0.000     0.000     0.000        1   Array#last                     
  0.00      0.000     0.000     0.000     0.000        1   Array#-                        
  0.00      0.000     0.000     0.000     0.000        1   Array#any?                     
  0.00      0.000     0.000     0.000     0.000        1   Hash#keys                      
  0.00      0.000     0.000     0.000     0.000        1   Array#pop
  ```

This turns the csv into an array with the split method and has a total time of ~4.8 seconds on average. I also added parameter which allows for the csv module to be used like before, in case there is a need for the module and/or its customizability.

If you would like for me to make any changes to the style, please let me know.

**Comment by Ashvith** [comment]
@pkeshkamat you might want to try using the `rake` command. Some of the tests are failing.

**Comment by ankane** [comment]
Hey @pkeshkamat, from what I can tell, there's a decent performance win from not passing the `headers` option to `CSV.read`/`CSV.parse`, so I think it'd be good to focus on that (rather than custom CSV parsing logic).

Also, please make sure the test suite passes (`bundle exec rake test`) and follow the existing style for indentation and spacing.

**Pull request closed without merging**
